[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "backend/src"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_ENV = "production"